@BaseUrl = http://localhost:5000/api/company/

### create Company
PUT {{BaseUrl}} HTTP/1.1
Content-Type:application/json

{
  "company_id": "1",
  "name": "TechNova GmbH",
  "company_number": "123456a",
  "company_info": "Innovative IT Lösungen in einer GmbH",
  "website": "https://technova.at",
  "email": "info@technova.at",
  "phone_number" : "015123456",
  "password": "pass123",
  "email_verified": "Y",
  "admin_verified": "Y",
  "company_registration_timestamp": "2025-05-21 08:24:50.637009"
}

