@BaseUrl = http://localhost:5000/api/company/

### create Company
PUT {{BaseUrl}} HTTP/1.1
Content-Type:application/json

{
  "company_id": "1",
  "name": "TechNova GmbH",
  "company_number": "123456a",
  "company_info": "Innovative IT Lösungen ",
  "website": "https://technova.at",
  "email": "info@technova.at",
  "phone_number" : "015123456",
  "password": "pass123",
  "email_verified": "Y",
  "admin_verified": "Y",
  "company_registration_timestamp": "2025-05-21 08:24:50.637009"
}

### create a new company
PUT {{BaseUrl}} HTTP/1.1
Content-Type:application/json

{
  "name": "GreenWave Solutions GmbH",
  "company_number": "654321b",
  "company_info": "Nachhaltige Energie- und Softwarelösungen",
  "website": "https://greenwave.at",
  "email": "kontakt@greenwave.at",
  "phone_number": "0123456789",
  "password": "securePass!2025",
  "email_verified": "N",
  "admin_verified": "N",
  "company_registration_timestamp": "2025-05-23 09:45:12.001",
  "email_verification_timestamp": null,
  "admin_verification_timestamp": null
}

### post a company login
POST {{BaseUrl}}company/login
Content-Type: application/json

{
  "email": "info@technova.at",
  "password": "pass123"
}

### delete a company
DELETE {{BaseUrl}}/8 HTTP/1.1

### delete a company that doesn't exist
DELETE {{BaseUrl}}/20000 HTTP/1.1

### verify the admin of a company
PATCH {{BaseUrl}}/9/verify_admin HTTP/1.1
Content-Type:application/json

{
  "admin_verified": "true"
}

### unverify the admin of a company
PATCH {{BaseUrl}}/9/verify_admin HTTP/1.1
Content-Type:application/json

{
  "admin_verified": "n"
}

### verify the email of a company
PATCH {{BaseUrl}}/8/verify_email HTTP/1.1
Content-Type:application/json

{
  "email_verified": "1"
}

### unverify the email of a company
PATCH {{BaseUrl}}/9/verify_email HTTP/1.1
Content-Type:application/json

{
  "email_verified": "no"
}
