@BaseUrl = http://localhost:5000/api/student/

### Post a new student
POST {{BaseUrl}}/
Content-Type: application/json

{
  "username": "if220197"
}

### Delete a student
DELETE {{BaseUrl}}/4

### Get all Admins
GET {{BaseUrl}}/admin/all